<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>RRRR</name>
  <uuid>884059da-6d8e-4dca-afd3-5900015eaa64</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
the employmentStatus is unemployed 
then
	set decision to 0.4;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
