<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>rule 1</name>
  <uuid>58d523ec-dc42-4088-957d-159aa4793d25</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the age of Customer is more than 65 and the international calls is less than 40 
then
	set decision to 0.4 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
